# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Graalvm JDK 22
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '22'
        distribution: 'graalvm'
        cache: maven
    - name: Build with Maven
      run: mvn -Pnative clean native:compile --file pom.xml
    - uses: actions/upload-artifact@v4
      with:
        name: mybatis-sample
        path: target/mybatis-sample
